### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by NinjutsuFish** [WSNCoding/Trump-Shooter#1]
We need to get someone to make a home screen with buttons

      ----------------
      NinjutsuFish
      ----------------

**Comment by PhantomArtist** [comment]
Will do. Any particular software?

**Comment by NinjutsuFish** [comment]
Soz but this is code based issue

**Comment by TheMiner63** [comment]
I can do buttons for the code in tkinter. please use Skype instead cos these threads r really annoying and confusing

**Comment by NinjutsuFish** [comment]
Hey all working on save game via database so the player will have to know SQL to change

**Comment by TheMiner63** [comment]
Why use sql that has nothing to do with local save data

**Comment by NinjutsuFish** [comment]
THIS IS USELESS

**Comment by NinjutsuFish** [comment]
lol

**Comment by NinjutsuFish** [comment]
can still comment
