### ISSUE TITLE
CHAT

### ISSUE THREAD

**Issue by NinjutsuFish** [WSNCoding/Trump-Shooter#2]
USE THISTO COMMENT ON AND CHAT WITH

**Comment by NinjutsuFish** [comment]
THIS IS A CHAT

**Comment by PhantomArtist** [comment]
OK

**Comment by NinjutsuFish** [comment]
Chit chat chit chat

**Comment by NinjutsuFish** [comment]
Da chat is being used

**Comment by NinjutsuFish** [comment]
Chit chat

**Comment by ReltonTolpo** [comment]
Hey, anyone on?

**Comment by Fishlips525** [comment]
No, I'm in Latin with Danny

**Comment by Kingdom03** [comment]
Hi

**Comment by TheMiner63** [comment]
Ori do you even understand imports because the beginning of all your programs are really sketchy with the imports no offence.

**Comment by NinjutsuFish** [comment]
hey

















































































































life

**Comment by NinjutsuFish** [comment]
im sorry im closing this usekess chat no one loved @TheMiner63

**Comment by NinjutsuFish** [comment]
`print("Invasion of the alliens")`

**Comment by NinjutsuFish** [comment]
done
